# Generated by Django 4.2 on 2023-05-02 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject1', models.CharField(max_length=255)),
                ('subject2', models.CharField(max_length=255)),
                ('subject3', models.CharField(max_length=255)),
                ('subject4', models.CharField(max_length=255)),
                ('subject5', models.CharField(max_length=255)),
                ('subject6', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='academic_id',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.academicyear'),
        ),
    ]
