# Generated by Django 4.2 on 2023-05-02 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_academicyear_student_academic_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='academic_id',
            new_name='academic_year_id',
        ),
    ]
