# Generated by Django 4.2 on 2023-05-02 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_academicyear_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='academic_year_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.academicyear'),
        ),
    ]
