# Generated by Django 4.2 on 2023-05-02 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_academic_year_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='name',
            field=models.CharField(choices=[(1, '1st yaer'), (2, '2st yaer'), (3, '3st yaer'), (4, '4st yaer')], default=1, max_length=1),
        ),
    ]
