# Generated by Django 4.2 on 2023-05-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_academicyear_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='name',
            field=models.PositiveIntegerField(choices=[(1, '1st yaer'), (2, '2st yaer'), (3, '3st yaer'), (4, '4st yaer')], default=1),
        ),
    ]
