# Generated by Django 4.2 on 2023-05-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_academicyear_subject1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_code', models.CharField(max_length=50)),
                ('sub_name', models.CharField(max_length=50)),
                ('sub_description', models.TextField()),
                ('sub_reference', models.CharField(max_length=100)),
                ('sub_teachers', models.ManyToManyField(blank=True, null=True, to='students.teachers')),
            ],
        ),
    ]
