# Generated by Django 4.2 on 2023-05-04 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_teachers_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='sub_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.academicyear'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sub_teachers',
            field=models.ManyToManyField(to='students.teachers'),
        ),
    ]
