# Generated by Django 4.2 on 2023-05-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_subject_sub_grade_alter_subject_sub_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='sub_teachers',
            field=models.ManyToManyField(blank=True, null=True, to='students.teachers'),
        ),
    ]
