# Generated by Django 4.2 on 2023-05-04 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_remove_subject_sub_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='sub_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.academicyear'),
        ),
    ]
