# Generated by Django 4.2 on 2023-05-05 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_teachers_tech_first_name_teachers_tech_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='tech_first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='tech_last_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
