# Generated by Django 4.2 on 2023-05-05 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_alter_teachers_tech_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='sub_teachers',
        ),
        migrations.AddField(
            model_name='subject',
            name='sub_teachers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.teachers'),
        ),
    ]
