# Generated by Django 4.2 on 2023-05-05 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_remove_subject_sub_teachers_subject_sub_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='subject1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sub_grade',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
