# Generated by Django 4.2 on 2023-05-05 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0023_alter_academicyear_subject1_alter_subject_sub_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='subject1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sub_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.academicyear'),
        ),
    ]
