# Generated by Django 4.2 on 2023-05-06 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0025_department_teacher_alter_subject_sub_teacher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='field_of_study',
        ),
    ]
